"""cria classes do modelo: Motorista, Veiculo, Cliente, Telefone, Instituicao, Endereco e Viagem

Revision ID: cc8d811cf737
Revises: 438dbc400dcd
Create Date: 2025-04-14 09:56:33.729691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8d811cf737'
down_revision = '438dbc400dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_cliente_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_cliente_nome'), ['nome'], unique=False)

    op.create_table('instituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instituicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instituicao_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_instituicao_nome'), ['nome'], unique=False)

    op.create_table('motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnh', sa.String(length=9), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('motorista', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_motorista_cnh'), ['cnh'], unique=True)
        batch_op.create_index(batch_op.f('ix_motorista_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_motorista_nome'), ['nome'], unique=False)

    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=64), nullable=False),
    sa.Column('rua', sa.String(length=64), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('bairro', sa.String(length=64), nullable=False),
    sa.Column('cidade', sa.String(length=64), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('complemento', sa.String(length=64), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endereco_bairro'), ['bairro'], unique=False)
        batch_op.create_index(batch_op.f('ix_endereco_cep'), ['cep'], unique=False)
        batch_op.create_index(batch_op.f('ix_endereco_cidade'), ['cidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_endereco_cliente_id'), ['cliente_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_endereco_complemento'), ['complemento'], unique=False)
        batch_op.create_index(batch_op.f('ix_endereco_instituicao_id'), ['instituicao_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_endereco_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_endereco_rua'), ['rua'], unique=False)
        batch_op.create_index(batch_op.f('ix_endereco_uf'), ['uf'], unique=False)

    op.create_table('telefone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=64), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telefone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telefone_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telefone_motorista_id'), ['motorista_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telefone_telefone'), ['telefone'], unique=True)

    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=64), nullable=False),
    sa.Column('modelo', sa.String(length=64), nullable=False),
    sa.Column('marca', sa.String(length=64), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veiculo_capacidade'), ['capacidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_veiculo_marca'), ['marca'], unique=False)
        batch_op.create_index(batch_op.f('ix_veiculo_modelo'), ['modelo'], unique=False)
        batch_op.create_index(batch_op.f('ix_veiculo_motorista_id'), ['motorista_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_veiculo_placa'), ['placa'], unique=True)

    op.create_table('viagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_corrida', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicao.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viagem_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_viagem_instituicao_id'), ['instituicao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_viagem_motorista_id'), ['motorista_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    with op.batch_alter_table('viagem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viagem_motorista_id'))
        batch_op.drop_index(batch_op.f('ix_viagem_instituicao_id'))
        batch_op.drop_index(batch_op.f('ix_viagem_cliente_id'))

    op.drop_table('viagem')
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veiculo_placa'))
        batch_op.drop_index(batch_op.f('ix_veiculo_motorista_id'))
        batch_op.drop_index(batch_op.f('ix_veiculo_modelo'))
        batch_op.drop_index(batch_op.f('ix_veiculo_marca'))
        batch_op.drop_index(batch_op.f('ix_veiculo_capacidade'))

    op.drop_table('veiculo')
    with op.batch_alter_table('telefone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telefone_telefone'))
        batch_op.drop_index(batch_op.f('ix_telefone_motorista_id'))
        batch_op.drop_index(batch_op.f('ix_telefone_cliente_id'))

    op.drop_table('telefone')
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endereco_uf'))
        batch_op.drop_index(batch_op.f('ix_endereco_rua'))
        batch_op.drop_index(batch_op.f('ix_endereco_numero'))
        batch_op.drop_index(batch_op.f('ix_endereco_instituicao_id'))
        batch_op.drop_index(batch_op.f('ix_endereco_complemento'))
        batch_op.drop_index(batch_op.f('ix_endereco_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_endereco_cidade'))
        batch_op.drop_index(batch_op.f('ix_endereco_cep'))
        batch_op.drop_index(batch_op.f('ix_endereco_bairro'))

    op.drop_table('endereco')
    with op.batch_alter_table('motorista', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motorista_nome'))
        batch_op.drop_index(batch_op.f('ix_motorista_cpf'))
        batch_op.drop_index(batch_op.f('ix_motorista_cnh'))

    op.drop_table('motorista')
    with op.batch_alter_table('instituicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instituicao_nome'))
        batch_op.drop_index(batch_op.f('ix_instituicao_cnpj'))

    op.drop_table('instituicao')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_nome'))
        batch_op.drop_index(batch_op.f('ix_cliente_email'))
        batch_op.drop_index(batch_op.f('ix_cliente_cpf'))

    op.drop_table('cliente')
    # ### end Alembic commands ###
